export const metadata = {
    title: "Contacts",
    description: "Generated by create next app",
};

import React, { ReactNode } from "react";

interface ContactsLayoutProps {
    children: ReactNode;
}

const ContactsLayout = ({ children }: ContactsLayoutProps) => {
    return <>{children}</>;
};

export default ContactsLayout;
